name: country
description: Generated country class with country_generator using countries.
version: 6.0.2
homepage: https://github.com/aaassseee/country
repository: https://github.com/aaassseee/country/tree/master/country
issue_tracker: https://github.com/aaassseee/country/issues

topics:
  - country
  - countries

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  build_runner: '>=2.0.0 <3.0.0'
  country_generator: '>=6.0.1 <7.0.0'
  flutter_lints: '>=6.0.0 <7.0.0'
  test: '>=1.0.0 <2.0.0'

#dependency_overrides:
#  country_generator:
#    path:
#      ../country_generator

country_generator:
  sourceFolder: submodule/countries
  outputFolder: lib/src